version: '3.7'

services:
  gateway:
    build: ./gateway
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./gateway:/app/
    container_name: gateway_app

  user_app:
    build: ./user
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    depends_on:
      - db_user
    env_file:
      - .env
    volumes:
      - ./user:/app/
    container_name: user_app

  db_user:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    ports:
      - '5430:5432'
    volumes:
      - ./data_user:/var/lib/postgresql/data/
    container_name: db_user

  author_app:
    build: ./author
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    depends_on:
      - db_author
    env_file:
      - .env
    volumes:
      - ./author:/app/
    container_name: author_app

  db_author:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_AUTHOR
    restart: always
    ports:
      - '5431:5432'
    volumes:
      - ./data_author:/var/lib/postgresql/data/
    container_name: db_author

  book_app:
    build: ./book
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    depends_on:
      - db_book
    env_file:
      - .env
    volumes:
      - ./book:/app/
    container_name: book_app

  db_book:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_BOOK
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data_book:/var/lib/postgresql/data
    container_name: db_book

  db_test:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER_TEST
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD_TEST
      POSTGRES_DB: $POSTGRES_DB_TEST
    restart: always
    volumes:
      - ./data_test/:/var/lib/postgresql/data
    container_name: db_test
