"""create book

Revision ID: 742505d2ab3b
Revises: 
Create Date: 2023-08-27 18:26:39.838213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742505d2ab3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    # ### end Alembic commands ###
