"""init author

Revision ID: 012d53a33879
Revises: 
Create Date: 2023-08-20 19:49:08.487588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012d53a33879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Author')
    # ### end Alembic commands ###
