"""add row refresh token

Revision ID: 0215ecacfd4d
Revises: 184f11d49b18
Create Date: 2023-09-11 18:29:51.965082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0215ecacfd4d'
down_revision = '184f11d49b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
