"""update row refresh token

Revision ID: cc2aba03ebf1
Revises: 0215ecacfd4d
Create Date: 2023-09-11 18:30:54.714027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2aba03ebf1'
down_revision = '0215ecacfd4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
